### ISSUE TITLE
snippets only working inside erb tags

### ISSUE THREAD

**Issue by scottbarrow** [tennantje/railsdev-sublime-snippets#11]
In a .html.erb file the snippet helper does not show when a keyword is typed
however, when inside erb tags in this file, the helper shows, however it also suffixes the erb tags, doubling up on erb tags. e.g. `<%= <%= link_to "Some Page", some_path %> %>`

**Comment by scottbarrow** [comment]
issue happens only on return and not tab

**Comment by tennantje** [comment]
Can't reproduce http://gfycat.com/QuickHatefulComet
